import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Provider} from "@/app/provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
      <Provider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
      >
        {children}
      </Provider>
      </body>
    </html>
  );
}
